In [2]:
import pandas as pd 
import numpy as np

In [3]:
people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'],
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'],
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

In [4]:
df = pd.DataFrame(people)

In [5]:
df

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                      NaN       36
4    NaN      NaN                      NaN      NaN
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [6]:
# to drop missing values 
df.dropna() # By default, running df.dropna() runs with specific background criteria

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
6     NA  Missing                       NA  Missing

In [7]:
# Customizing the  dropna() Criteria
df.dropna(axis='index',how='any')
# here any drops any rows that are missing

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
6     NA  Missing                       NA  Missing

In [8]:
df.dropna(axis='index',how='all')
# it will drop only rows, where all the elements are misiing

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                      NaN       36
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [9]:
df.dropna(axis='columns',how='all')
# axis='columns' and how='all' .
# as there no any columns have complete missing values so all the columns and rows are there

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                      NaN       36
4    NaN      NaN                      NaN      NaN
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [10]:
# and if axis='columns' and how='any' will drop all column containing even a single missing value.
df.dropna(axis='columns',how ='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

# Filtering by Specific Columns (subset)

In [11]:
# If you only want to drop rows missing data in a critical column (e.g., an email address)
df.dropna(axis='index',how='any',subset=['email'])
# here does not any impact that either we use how ='any' or how = 'all', it will give same results 
# as we are checking for a single (one) value

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [12]:
#To check multiple columns where a row is dropped only if both are missing, combine
df.dropna(axis ='index',how='all',subset =['last','email'])
# here all works similar to (AND operation ) , i.e. drop only if both last and email are misssing in a specific row

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                      NaN       36
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [13]:
df.dropna(axis ='index',how='any',subset =['last','email'])
# here 'any' works similar to ( OR operations) means it will drop if any of last or email is missing or both.

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
6     NA  Missing                       NA  Missing

 # 2. Handling Custom Missing Values that we passed as string

In [14]:
df.replace('NA',np.nan,inplace=True)
df.replace('Missing',np.nan,inplace= True)

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN                      NaN  NaN
5    NaN      NaN      Anonymous@email.com  NaN
6    NaN      NaN                      NaN  NaN

In [15]:
df.dropna(axis='index',how='all')

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
5    NaN      NaN      Anonymous@email.com  NaN

In [16]:
df.dropna(axis='index',how='any')

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [17]:
df.isna()
# df.isna() is the method used to detect missing values across your entire dataset.
# true means na is present

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [18]:
df.replace('Missing',np.nan,inplace= True)

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN                      NaN  NaN
5    NaN      NaN      Anonymous@email.com  NaN
6    NaN      NaN                      NaN  NaN

In [22]:
df = df.fillna(0)

In [23]:
df.head()

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63
3  Chris  Schafer                        0  36
4      0        0                        0   0

In [ ]:
df['age'].mean()

TypeError: can only concatenate str (not "int") to str