In [1227]:
# creating a dictonary

people = {
    "first":["corey","john","harry"],
    "last" : ["schafer","cena","potter"],
    "email":[ "coreyschafer@gmail.com","johncena@gmai;.com","harrypotter@gmail.com"]
             
}

In [1228]:
people["email"] # to access information within dictonary

['coreyschafer@gmail.com', 'johncena@gmai;.com', 'harrypotter@gmail.com']

In [1229]:
# creating a dataframe using a dictonary (people)
import pandas as pd

In [1230]:
df = pd.DataFrame(people)
df

   first     last                   email
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry   potter   harrypotter@gmail.com

In [1231]:
df["email"] # to access information within dataframe ,
# better way to access

# outputs will be series object

0    coreyschafer@gmail.com
1        johncena@gmai;.com
2     harrypotter@gmail.com
Name: email, dtype: str

In [1232]:
type(df["email"])

pandas.Series

In [1233]:
# alternate way to access information within dataframe
df.email

0    coreyschafer@gmail.com
1        johncena@gmai;.com
2     harrypotter@gmail.com
Name: email, dtype: str

In [1234]:
# to access multiple information
df[['email','last']] # list ['email','last'] is passed inside this bracket []
# i.e. df[list]. and list = ['email','last']

# NOTE - as we are accessing more than one info. the outputs will now not same as previoulsy as series 
# now the outputs will be dataframe and later we can extract information from them

                    email     last
0  coreyschafer@gmail.com  schafer
1      johncena@gmai;.com     cena
2   harrypotter@gmail.com   potter

In [1235]:
df.columns # to access column info.

Index(['first', 'last', 'email'], dtype='str')

In [1236]:
df.iloc[0] # to access row info having index 0 , i.e. 1st row
# & index here will be column name so we can clearly see what info. represnating what

first                     corey
last                    schafer
email    coreyschafer@gmail.com
Name: 0, dtype: str

In [1237]:
df.iloc[[0,1]]
# to access multiple rows

   first     last                   email
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com

In [1238]:
# To access row along with columns to
df.iloc[[0,1],2]

# here  first argument [0, 1] selects the rows, and the second argument 2 selects the third column (index 2)

0    coreyschafer@gmail.com
1        johncena@gmai;.com
Name: email, dtype: str

In [1239]:
df.loc[0]

first                     corey
last                    schafer
email    coreyschafer@gmail.com
Name: 0, dtype: str

In [1240]:
df.loc[[0,1]]

   first     last                   email
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com

In [1241]:
# if we want only first column i.e. first name columns then 
df.loc[[0,1],"first"]
# error if we directly write df.loc[[0,1],0]

0    corey
1     john
Name: first, dtype: str

In [1242]:
# if we want email and first name To
df.loc[[0,1],['first','email']]

   first                   email
0  corey  coreyschafer@gmail.com
1   john      johncena@gmai;.com

In [1243]:
df.loc[[0],['first','last']]

   first     last
0  corey  schafer

In [1244]:
df.loc[len(df)] = ['Roman','cena','Romancena@gmail.com']
df

   first     last                   email
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry   potter   harrypotter@gmail.com
3  Roman     cena     Romancena@gmail.com

NOW  USING CONCEPTS OF FILTERING

In [1245]:
df['last'] == 'cena' # to check whether cena is the. last name or not , if the answer is true then is yes , or not is false

0    False
1     True
2    False
3     True
Name: last, dtype: bool

In [1246]:
filt = (df['last']== 'cena') # created a varible as filt . instead of filter becoz 'filter' is python built in function

In [1247]:
df[filt]

   first  last                email
1   john  cena   johncena@gmai;.com
3  Roman  cena  Romancena@gmail.com

In [1248]:
df.loc[filt,'email'] # now we can get any info. of elements having last = cena .

1     johncena@gmai;.com
3    Romancena@gmail.com
Name: email, dtype: str

In [1249]:
# let if we want first name = john and last name = cena then 
filt1 = (df['last'] == 'cena') & (df['first'] == 'john') # using AND (&) 
df[filt1]

  first  last               email
1  john  cena  johncena@gmai;.com

In [1250]:
# using OR(|)
filt2 = (df['last'] =='cena') | (df['first'] =='corey')
df[filt2]

   first     last                   email
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
3  Roman     cena     Romancena@gmail.com

In [1251]:
df.loc[~filt2,'email'] # ~filt2 will gives out ouputs of elements other than which full filled this conditions

2    harrypotter@gmail.com
Name: email, dtype: str

LECTURE 05 - Updating Rows & Columns - modifying data within dataframes

In [1252]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [1253]:
df.columns = ['first_name','last_name','email']
df.columns

Index(['first_name', 'last_name', 'email'], dtype='str')

In [1254]:
# to convert coulumns into uppercase 
df.columns = [x.upper() for x in df.columns]
df

  FIRST_NAME LAST_NAME                   EMAIL
0      corey   schafer  coreyschafer@gmail.com
1       john      cena      johncena@gmai;.com
2      harry    potter   harrypotter@gmail.com
3      Roman      cena     Romancena@gmail.com

In [1255]:
# to replaces spaces with _ . for example if there is a coloumn name first name , then df. first name will show and error message 
# so we need to add _ b/w them for example first_name
df.columns = df.columns.str.replace(' ','_') # it will convert spaces into _
df

  FIRST_NAME LAST_NAME                   EMAIL
0      corey   schafer  coreyschafer@gmail.com
1       john      cena      johncena@gmai;.com
2      harry    potter   harrypotter@gmail.com
3      Roman      cena     Romancena@gmail.com

In [1256]:
# what if  we we wanted to do some changes in specific columns 
# let we wanted to change first_name and last_name as first and last
df.rename(columns={'FIRST_NAME': 'first' , 'LAST_NAME':'last'}, inplace=True)
df

   first     last                   EMAIL
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry   potter   harrypotter@gmail.com
3  Roman     cena     Romancena@gmail.com

In [1257]:
# UPDATING DATA IN A ROWS 
df.loc[3] = ['Roman','reings','romanreings@gmail.com']
df

   first     last                   EMAIL
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry   potter   harrypotter@gmail.com
3  Roman   reings   romanreings@gmail.com

In [1258]:
# lets again we wanted to change the name roman reings as roman cena 
df.loc[3,[ 'last','EMAIL']]  = ['cena','romancena@gmail.com']
df

   first     last                   EMAIL
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry   potter   harrypotter@gmail.com
3  Roman     cena     romancena@gmail.com

In [1259]:
df.loc[2,'last'] = 'wonder'
df

   first     last                   EMAIL
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry   wonder   harrypotter@gmail.com
3  Roman     cena     romancena@gmail.com

In [1260]:
# Alternate method by using at
df.at[2,'last'] = 'potter'
df

   first     last                   EMAIL
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry   potter   harrypotter@gmail.com
3  Roman     cena     romancena@gmail.com

In [1261]:
filt = (df['EMAIL'] == 'harrypotter@gmail.com')
df[filt]

   first    last                  EMAIL
2  harry  potter  harrypotter@gmail.com

In [1262]:
# IS WE WANT TO ACESSS ONLY LAST NAME THEN WE CAN DO LIKE 
filt = (df['EMAIL'] == 'harrypotter@gmail.com')
df[filt]['last']

2    potter
Name: last, dtype: str

In [1263]:
# trying to update single row of data 
filt = (df['EMAIL'] == 'harrypotter@gmail.com')
df[filt]['last'] = ['kane']

/var/folders/81/0vymtr1s7xz06fvcc28tzjsw0000gn/T/ipykernel_14700/219342881.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[filt]['last'] = ['kane']

In [1264]:
# so to fix the above error we have to use loc function 
filt = (df['EMAIL'] == 'harrypotter@gmail.com')
df.loc[filt,'last'] = ['kane']
df

   first     last                   EMAIL
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry     kane   harrypotter@gmail.com
3  Roman     cena     romancena@gmail.com

In [1265]:
# updating multiple row of data 
# let convert all tge emails to lowercase 

df['EMAIL'] = df['EMAIL'].str.lower()
df

   first     last                   EMAIL
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry     kane   harrypotter@gmail.com
3  Roman     cena     romancena@gmail.com

apply.    
map.    
applymap.    
replace.

apply: Runs a function element-wise on a Series, or axis-wise on a DataFrame.

map: Swaps out specific values in a Series using a lookup dictionary.

applymap: Runs a function on every single individual element across an entire DataFrame.

replace: Swaps values in a Series without accidentally wiping out unmapped fields.

In [1266]:
# apply

In [1267]:
df['EMAIL'].apply(len)

0    22
1    18
2    21
3    19
Name: EMAIL, dtype: int64

In [1268]:
def update_email(EMAIL):
    return EMAIL.upper()
df['EMAIL'] = df['EMAIL'].apply(update_email)
df['EMAIL']

0    COREYSCHAFER@GMAIL.COM
1        JOHNCENA@GMAI;.COM
2     HARRYPOTTER@GMAIL.COM
3       ROMANCENA@GMAIL.COM
Name: EMAIL, dtype: str

lambda function

In [1269]:
df['EMAIL'] = df['EMAIL'].apply(lambda x : x.lower())

df # using lamba funtion

   first     last                   EMAIL
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry     kane   harrypotter@gmail.com
3  Roman     cena     romancena@gmail.com

In [1270]:
df['EMAIL'].apply(len) # it will give the aplhabet that are in email

0    22
1    18
2    21
3    19
Name: EMAIL, dtype: int64

In [1271]:
df.apply(len) # it will give no. of rows .

first    4
last     4
EMAIL    4
dtype: int64

In [1272]:
df.apply(len, axis= 1) # it will give a number of columns

0    3
1    3
2    3
3    3
dtype: int64

In [1273]:
# let say we want to grab minimum value from each column then 
df.apply(pd.Series.min)

first                     Roman
last                       cena
EMAIL    coreyschafer@gmail.com
dtype: str

In [1274]:
df.apply(lambda x : x.min())

first                     Roman
last                       cena
EMAIL    coreyschafer@gmail.com
dtype: str

# map

In [1275]:
df.map(len)

   first  last  EMAIL
0      5     7     22
1      4     4     18
2      5     4     21
3      5     4     19

In [1276]:
df.map(str.upper)

   first     last                   EMAIL
0  COREY  SCHAFER  COREYSCHAFER@GMAIL.COM
1   JOHN     CENA      JOHNCENA@GMAI;.COM
2  HARRY     KANE   HARRYPOTTER@GMAIL.COM
3  ROMAN     CENA     ROMANCENA@GMAIL.COM

In [1277]:
df.map(str.lower)

   first     last                   EMAIL
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry     kane   harrypotter@gmail.com
3  roman     cena     romancena@gmail.com

In [1278]:
print(df['first'])

0    corey
1     john
2    harry
3    Roman
Name: first, dtype: str

In [1279]:
df['first'] = df['first'].replace({'corey':'chris','harry':'henry'})
df

   first     last                   EMAIL
0  chris  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  henry     kane   harrypotter@gmail.com
3  Roman     cena     romancena@gmail.com

In [1280]:
df['first'] = df['first'].map({'chris':'chris','Roman':'henry'})
df

   first     last                   EMAIL
0  chris  schafer  coreyschafer@gmail.com
1    NaN     cena      johncena@gmai;.com
2    NaN     kane   harrypotter@gmail.com
3  henry     cena     romancena@gmail.com

In [1281]:
df['first'] = df['first'].map({''})

TypeError: 'set' object is not callable

In [ ]:
df.loc[1, 'first'] = 'john' # to fill the na value
df.loc[2, 'first'] = 'henry'

In [ ]:
df

   first     last                   EMAIL
0  chris  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  henry     kane   harrypotter@gmail.com
3  henry     cena     romancena@gmail.com

# Add/Remove rows & columns

In [ ]:
df['full_name'] = df['first'] + ' ' + df['last']
df

   first     last                   EMAIL      full_name
0  chris  schafer  coreyschafer@gmail.com  chris schafer
1    NaN     cena      johncena@gmai;.com            NaN
2    NaN     kane   harrypotter@gmail.com            NaN
3  henry     cena     romancena@gmail.com     henry cena

In [ ]:
df.drop(columns=['first','last'],inplace=True)

In [ ]:
df

                    EMAIL      full_name
0  coreyschafer@gmail.com  chris schafer
1      johncena@gmai;.com            NaN
2   harrypotter@gmail.com            NaN
3     romancena@gmail.com     henry cena

In [ ]:
df['full_name'].str.split(' ')

0    [chris, schafer]
1                 NaN
2                 NaN
3       [henry, cena]
Name: full_name, dtype: object

In [ ]:
df['full_name'].str.split(' ',expand=True)

       0        1
0  chris  schafer
1    NaN      NaN
2    NaN      NaN
3  henry     cena

In [ ]:
df[['first','last']] = df['full_name'].str.split(' ',expand=True)
df

                    EMAIL      full_name  first     last
0  coreyschafer@gmail.com  chris schafer  chris  schafer
1      johncena@gmai;.com            NaN    NaN      NaN
2   harrypotter@gmail.com            NaN    NaN      NaN
3     romancena@gmail.com     henry cena  henry     cena

In [ ]:
new_row = pd.DataFrame([{'first':'alex','last':'carry'}])
df = pd.concat([df,new_row])

In [ ]:
df

                    EMAIL      full_name  first     last
0  coreyschafer@gmail.com  chris schafer  chris  schafer
1      johncena@gmai;.com            NaN    NaN      NaN
2   harrypotter@gmail.com            NaN    NaN      NaN
3     romancena@gmail.com     henry cena  henry     cena
0                     NaN            NaN   alex    carry

In [ ]:

avengers = {
    "first":["captain","black","henry","corey"],
    "last" : ["america","panther","potter","malan"],
    "EMAIL":[ "captainamerica@gmail.com","panther@gmai;.com","harrypotter@gmail.com","coreymalan@gmail.com"]
             
}

In [1283]:
df2 = pd.DataFrame(avengers)
df2

     first     last                     EMAIL
0  captain  america  captainamerica@gmail.com
1    black  panther         panther@gmai;.com
2    henry   potter     harrypotter@gmail.com
3    corey    malan      coreymalan@gmail.com

In [1284]:
df = pd.concat([df, df2], ignore_index=True)
df

     first     last                     EMAIL
0    chris  schafer    coreyschafer@gmail.com
1      NaN     cena        johncena@gmai;.com
2      NaN     kane     harrypotter@gmail.com
3    henry     cena       romancena@gmail.com
4  captain  america  captainamerica@gmail.com
5    black  panther         panther@gmai;.com
6    henry   potter     harrypotter@gmail.com
7    corey    malan      coreymalan@gmail.com

In [ ]:
#df = df.drop(index=[5, 6, 9,10]) # to drop specific columns

In [ ]:
df

     first     last                     EMAIL
0    chris  schafer    coreyschafer@gmail.com
1      NaN     cena        johncena@gmai;.com
2      NaN     kane     harrypotter@gmail.com
3    henry     cena       romancena@gmail.com
4  captain  america  captainamerica@gmail.com
5    black  panther         panther@gmai;.com
6    harry   potter     harrypotter@gmail.com
7    corey    malan      coreymalan@gmail.com

In [1285]:
# df = df.drop(columns=['email'])
df

     first     last                     EMAIL
0    chris  schafer    coreyschafer@gmail.com
1      NaN     cena        johncena@gmai;.com
2      NaN     kane     harrypotter@gmail.com
3    henry     cena       romancena@gmail.com
4  captain  america  captainamerica@gmail.com
5    black  panther         panther@gmai;.com
6    henry   potter     harrypotter@gmail.com
7    corey    malan      coreymalan@gmail.com

# SORTING DATA

In [1286]:
df.sort_values(by = 'last') # this will sort values according to last as assending order by default

     first     last                     EMAIL
4  captain  america  captainamerica@gmail.com
1      NaN     cena        johncena@gmai;.com
3    henry     cena       romancena@gmail.com
2      NaN     kane     harrypotter@gmail.com
7    corey    malan      coreymalan@gmail.com
5    black  panther         panther@gmai;.com
6    henry   potter     harrypotter@gmail.com
0    chris  schafer    coreyschafer@gmail.com

In [1287]:
df.sort_values(by = "last",ascending=False) # this will sort values by descending order

     first     last                     EMAIL
0    chris  schafer    coreyschafer@gmail.com
6    henry   potter     harrypotter@gmail.com
5    black  panther         panther@gmai;.com
7    corey    malan      coreymalan@gmail.com
2      NaN     kane     harrypotter@gmail.com
1      NaN     cena        johncena@gmai;.com
3    henry     cena       romancena@gmail.com
4  captain  america  captainamerica@gmail.com

In [1289]:
# Multi-Column Sorting
df.sort_values(by=['last','EMAIL'],ascending=[False,True],inplace = True)
# this will sort the values at first according to last in descending order then according to email (ascending)
# if there is common last name found

In [1290]:
df

     first     last                     EMAIL
0    chris  schafer    coreyschafer@gmail.com
6    henry   potter     harrypotter@gmail.com
5    black  panther         panther@gmai;.com
7    corey    malan      coreymalan@gmail.com
2      NaN     kane     harrypotter@gmail.com
1      NaN     cena        johncena@gmai;.com
3    henry     cena       romancena@gmail.com
4  captain  america  captainamerica@gmail.com