In [1]:
# creating a dictonary

people = {
    "first":["corey","john","harry"],
    "last" : ["schafer","cena","potter"],
    "email":[ "coreyschafer@gmail.com","johncena@gmai;.com","harrypotter@gmail.com"]
             
}

In [2]:
people["email"] # to access information within dictonary

['coreyschafer@gmail.com', 'johncena@gmai;.com', 'harrypotter@gmail.com']

In [3]:
# creating a dataframe using a dictonary (people)
import pandas as pd

In [4]:
df = pd.DataFrame(people)
df

   first     last                   email
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry   potter   harrypotter@gmail.com

In [5]:
df["email"] # to access information within dataframe ,
# better way to access

# outputs will be series object

0    coreyschafer@gmail.com
1        johncena@gmai;.com
2     harrypotter@gmail.com
Name: email, dtype: str

In [6]:
type(df["email"])

pandas.Series

In [7]:
# alternate way to access information within dataframe
df.email

0    coreyschafer@gmail.com
1        johncena@gmai;.com
2     harrypotter@gmail.com
Name: email, dtype: str

In [8]:
# to access multiple information
df[['email','last']] # list ['email','last'] is passed inside this bracket []
# i.e. df[list]. and list = ['email','last']

# NOTE - as we are accessing more than one info. the outputs will now not same as previoulsy as series 
# now the outputs will be dataframe and later we can extract information from them

                    email     last
0  coreyschafer@gmail.com  schafer
1      johncena@gmai;.com     cena
2   harrypotter@gmail.com   potter

In [9]:
df.columns # to access column info.

Index(['first', 'last', 'email'], dtype='str')

In [10]:
df.iloc[0] # to access row info having index 0 , i.e. 1st row
# & index here will be column name so we can clearly see what info. represnating what

first                     corey
last                    schafer
email    coreyschafer@gmail.com
Name: 0, dtype: str

In [11]:
df.iloc[[0,1]]
# to access multiple rows

   first     last                   email
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com

In [12]:
# To access row along with columns to
df.iloc[[0,1],2]

# here  first argument [0, 1] selects the rows, and the second argument 2 selects the third column (index 2)

0    coreyschafer@gmail.com
1        johncena@gmai;.com
Name: email, dtype: str

In [13]:
df.loc[0]

first                     corey
last                    schafer
email    coreyschafer@gmail.com
Name: 0, dtype: str

In [14]:
df.loc[[0,1]]

   first     last                   email
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com

In [15]:
# if we want only first column i.e. first name columns then 
df.loc[[0,1],"first"]
# error if we directly write df.loc[[0,1],0]

0    corey
1     john
Name: first, dtype: str

In [17]:
# if we want email and first name To
df.loc[[0,1],['first','email']]

   first                   email
0  corey  coreyschafer@gmail.com
1   john      johncena@gmai;.com

In [18]:
df.loc[[0],['first','last']]

   first     last
0  corey  schafer